/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 .\public\models\ring1.glb
*/
import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'


const material = new THREE.MeshPhysicalMaterial({
  color: new THREE.Color('#F9F1FB').convertSRGBToLinear(),
  roughness: 0,
  clearcoat: 0.1,
  opacity: 0.3,
  clearcoatRoughness: 0.5,
})

const material2 = new THREE.MeshStandardMaterial( {

    color: new THREE.Color('#FFF0B9').convertSRGBToLinear(),
    roughness: 0.3,
    metalness: 1,


} );

export function Model1(props) {
  const { nodes, materials } = useGLTF('/models/ring1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.imagetostl_mesh0.geometry} material={material} />
      <mesh geometry={nodes.imagetostl_mesh1.geometry} material={material} />
      <mesh geometry={nodes.imagetostl_mesh2.geometry} material={material} />
      <mesh geometry={nodes.imagetostl_mesh3.geometry} material={material} />
      <mesh geometry={nodes.imagetostl_mesh4.geometry} material={material} />
      <mesh geometry={nodes.imagetostl_mesh5.geometry} material={material} />
      <mesh geometry={nodes.imagetostl_mesh6.geometry} material={material} />
      <mesh geometry={nodes.imagetostl_mesh7.geometry} material={material} />
      <mesh geometry={nodes.imagetostl_mesh8.geometry} material={material} />
      <mesh geometry={nodes.imagetostl_mesh9.geometry} material={material} />
      <mesh geometry={nodes.imagetostl_mesh10.geometry} material={material} />
      <mesh geometry={nodes.imagetostl_mesh11.geometry} material={material} />
      <mesh geometry={nodes.imagetostl_mesh12.geometry} material={material} />
      <mesh geometry={nodes.imagetostl_mesh13.geometry} material={material} />
      <mesh geometry={nodes.imagetostl_mesh14.geometry} material={material} />
      <mesh geometry={nodes.imagetostl_mesh15.geometry} material={material} />
      <mesh geometry={nodes.imagetostl_mesh16.geometry} material={material2} />
      <mesh geometry={nodes.imagetostl_mesh17.geometry} material={material} />
      <mesh geometry={nodes.imagetostl_mesh18.geometry} material={material} />
      <mesh geometry={nodes.imagetostl_mesh19.geometry} material={material} />
      <mesh geometry={nodes.imagetostl_mesh20.geometry} material={material} />
    </group>
  )
}

useGLTF.preload('/models/ring1.glb')
