/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 .\public\models\ring2.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model2(props) {
  const { nodes, materials } = useGLTF('/models/ring2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.imagetostl_mesh0.geometry} material={materials.mat0} />
      <mesh geometry={nodes.imagetostl_mesh1.geometry} material={materials.mat1} />
      <mesh geometry={nodes.imagetostl_mesh2.geometry} material={materials.mat2} />
      <mesh geometry={nodes.imagetostl_mesh3.geometry} material={materials.mat3} />
      <mesh geometry={nodes.imagetostl_mesh4.geometry} material={materials.mat4} />
      <mesh geometry={nodes.imagetostl_mesh5.geometry} material={materials.mat5} />
      <mesh geometry={nodes.imagetostl_mesh6.geometry} material={materials.mat6} />
      <mesh geometry={nodes.imagetostl_mesh7.geometry} material={materials.mat7} />
      <mesh geometry={nodes.imagetostl_mesh8.geometry} material={materials.mat8} />
      <mesh geometry={nodes.imagetostl_mesh9.geometry} material={materials.mat9} />
      <mesh geometry={nodes.imagetostl_mesh10.geometry} material={materials.mat10} />
      <mesh geometry={nodes.imagetostl_mesh11.geometry} material={materials.mat11} />
      <mesh geometry={nodes.imagetostl_mesh12.geometry} material={materials.mat12} />
      <mesh geometry={nodes.imagetostl_mesh13.geometry} material={materials.mat13} />
      <mesh geometry={nodes.imagetostl_mesh14.geometry} material={materials.mat14} />
      <mesh geometry={nodes.imagetostl_mesh15.geometry} material={materials.mat15} />
      <mesh geometry={nodes.imagetostl_mesh16.geometry} material={materials.mat16} />
      <mesh geometry={nodes.imagetostl_mesh17.geometry} material={materials.mat17} />
      <mesh geometry={nodes.imagetostl_mesh18.geometry} material={materials.mat18} />
      <mesh geometry={nodes.imagetostl_mesh19.geometry} material={materials.mat19} />
      <mesh geometry={nodes.imagetostl_mesh20.geometry} material={materials.mat20} />
      <mesh geometry={nodes.imagetostl_mesh21.geometry} material={materials.mat21} />
      <mesh geometry={nodes.imagetostl_mesh22.geometry} material={materials.mat22} />
      <mesh geometry={nodes.imagetostl_mesh23.geometry} material={materials.mat23} />
      <mesh geometry={nodes.imagetostl_mesh24.geometry} material={materials.mat24} />
      <mesh geometry={nodes.imagetostl_mesh25.geometry} material={materials.mat25} />
      <mesh geometry={nodes.imagetostl_mesh26.geometry} material={materials.mat26} />
      <mesh geometry={nodes.imagetostl_mesh27.geometry} material={materials.mat27} />
      <mesh geometry={nodes.imagetostl_mesh28.geometry} material={materials.mat28} />
      <mesh geometry={nodes.imagetostl_mesh29.geometry} material={materials.mat29} />
      <mesh geometry={nodes.imagetostl_mesh30.geometry} material={materials.mat30} />
      <mesh geometry={nodes.imagetostl_mesh31.geometry} material={materials.mat31} />
      <mesh geometry={nodes.imagetostl_mesh32.geometry} material={materials.mat32} />
      <mesh geometry={nodes.imagetostl_mesh33.geometry} material={materials.mat33} />
      <mesh geometry={nodes.imagetostl_mesh34.geometry} material={materials.mat34} />
      <mesh geometry={nodes.imagetostl_mesh35.geometry} material={materials.mat35} />
      <mesh geometry={nodes.imagetostl_mesh36.geometry} material={materials.mat36} />
      <mesh geometry={nodes.imagetostl_mesh37.geometry} material={materials.mat37} />
      <mesh geometry={nodes.imagetostl_mesh38.geometry} material={materials.mat38} />
      <mesh geometry={nodes.imagetostl_mesh39.geometry} material={materials.mat39} />
      <mesh geometry={nodes.imagetostl_mesh40.geometry} material={materials.mat40} />
      <mesh geometry={nodes.imagetostl_mesh41.geometry} material={materials.mat41} />
      <mesh geometry={nodes.imagetostl_mesh42.geometry} material={materials.mat42} />
      <mesh geometry={nodes.imagetostl_mesh43.geometry} material={materials.mat43} />
      <mesh geometry={nodes.imagetostl_mesh44.geometry} material={materials.mat44} />
      <mesh geometry={nodes.imagetostl_mesh45.geometry} material={materials.mat45} />
    </group>
  )
}

useGLTF.preload('/models/ring2.glb')
